### ISSUE TITLE
[CI/CD] Github PR 생성 시에 403

### ISSUE THREAD

**Issue by ye-geeee** [TTeYY/zipzup#19]
https://github.com/TTeYY/zipzup/actions/runs/3902876427/jobs/6666475516

```
RequestError [HttpError]: GitHub Actions is not permitted to create or approve pull requests.
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:6172:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13356:16), <anonymous>:5:18)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:13452:20) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/TTeYY/zipzup/pulls',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 12 Jan 2023 13:51:54 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=[31](https://github.com/TTeYY/zipzup/actions/runs/3902876427/jobs/6666475516#step:5:32)536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3',
      'x-github-request-id': 'A480:02BA:CAB02B:1A0934C:63C01079',
      'x-ratelimit-limit': '1000',
      'x-ratelimit-remaining': '979',
      'x-ratelimit-reset': '16735[33](https://github.com/TTeYY/zipzup/actions/runs/3902876427/jobs/6666475516#step:5:34)624',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '21',
      'x-xss-protection': '0'
```

**Comment by ye-geeee** [comment]
organization에 권한 줘서 해결
